### ISSUE TITLE
Same Tag Title for 2 different products throws error

### ISSUE THREAD

**Issue by vishnunarayananb** [Sameera-Perera/Flutter-Grocery-App#1]
Say 2 products which is of 100g with different prices. For one product I give the title as 100g with price of 5$ and  for a  different product I give  title as 100g with price of 7$. When I run the app I get the following error.

```
          throw FlutterError.fromParts(<DiagnosticsNode>[
            ErrorSummary('There are multiple heroes that share the same tag within a subtree.'),
            ErrorDescription(
              'Within each subtree for which heroes are to be animated (i.e. a PageRoute subtree), '
              'each Hero must have a unique non-null tag.\n'
              'In this case, multiple heroes had the following tag: $tag',
            ),
```
Is there a way to give same title with varying prices for different products.

**Comment by Sameera-Perera** [comment]
This issue is normally come if we use duplicate tag id in Hero tag. In here I user "product.images.first" as a tag. try to change it with product.id or any unique value for each product.
