### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The method 'map' was called on null

### ISSUE THREAD

**Issue by webx20** [Sameera-Perera/Flutter-Grocery-App#2]
Hello sir. I tried your code out to see but i keep getting this error can you help? I wasn't getting it before just recently

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: NoSuchMethodError: The method 'map' was called on null.
E/flutter ( 5813): Receiver: null
E/flutter ( 5813): Tried calling: map(Closure: (dynamic) => AdBanner)

**Comment by Sameera-Perera** [comment]
Data fetching has issue. Please check if fetch result have data.
try - print(result.body);
if print is null or error, check your searvice method.
